name = "SUNRepresentations"
uuid = "1a50b95c-7aac-476d-a9ce-2bfc675fc617"
authors = ["Maarten Van Damme <Maarten.VanDamme@UGent.be>, Jutho Haegeman <jutho.haegeman@ugent.be> and Lukas Devos <lukas.devos@UGent.be>"]
version = "0.2.2"

[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Pidfile = "fa939f87-e72e-5be4-a000-7fc836dbe307"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
RationalRoots = "308eb6b3-cc68-5ff3-9e97-c3c4da4fa681"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
SparseArrayKit = "a9a3c162-d163-4c15-8926-b8794fbefed2"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"

[weakdeps]
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"

[extensions]
SUNRepresentationsLatexifyExt = "Latexify"

[compat]
Aqua = "0.6, 0.7, 0.8"
Combinatorics = "1"
JLD2 = "0.5"
LRUCache = "1.6"
Latexify = "0.16"
LinearAlgebra = "1"
Pidfile = "1.3"
Preferences = "1.2"
Random = "1"
RationalRoots = "0.1 - 0.2"
Scratch = "1"
SparseArrayKit = "0.3"
TensorKit = "0.11, 0.12, 0.14"
TensorOperations = "4"
Test = "1"
TestExtras = "0.2"
TupleTools = "1.4"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestExtras = "5ed8adda-3752-4e41-b88a-e8b09835ee3a"
TupleTools = "9d95972d-f1c8-5527-a6e0-b4b365fa01f6"

[targets]
test = ["Test", "Random", "Combinatorics", "TestExtras", "TensorKit", "TupleTools", "Latexify", "Aqua"]
