name = "SUNRepresentations"
uuid = "1a50b95c-7aac-476d-a9ce-2bfc675fc617"
authors = ["Maarten Van Damme <Maarten.VanDamme@UGent.be> and Jutho Haegeman <jutho.haegeman@ugent.be>"]
version = "0.1.3"

[deps]
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RationalRoots = "308eb6b3-cc68-5ff3-9e97-c3c4da4fa681"
SparseArrayKit = "a9a3c162-d163-4c15-8926-b8794fbefed2"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"

[compat]
RationalRoots = "0.1 - 0.2"
SparseArrayKit = "0.2"
TensorKit = "0.9 - 0.20,1"
TensorOperations = "3"
julia = "1.4 - 1.7"

[extras]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestExtras = "5ed8adda-3752-4e41-b88a-e8b09835ee3a"
TupleTools = "9d95972d-f1c8-5527-a6e0-b4b365fa01f6"

[targets]
test = ["Test", "Random", "Combinatorics", "TestExtras", "TensorKit", "TupleTools"]
